### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajbhoyar729**
Added  discription

VS code:-

[musm/min-tomorrow-theme](https://github.com/musm/min-tomorrow-theme)]

Typescript

[LBBO/generate-web-app](https://github.com/LBBO/generate-web-app)]

### CODE REVIEW

**Review by vivian-dai — APPROVED** [review]
LGTM, happy hacking!

**Comment by rajbhoyar729** [comment]
i  am  sry  there  is  one  more  left  in this  list   i  am  doing that  right  and  ha  sry  for the  misstake

**Comment by vivian-dai** [comment]
Oh whoops, I'll revert the pull request

**Comment by vivian-dai** [comment]
Or actually, just make another pull request, it's ok

**Pull request merged**
