### PR TITLE
added leetcode problme solution repo

### PR DESCRIPTION
**Pull request by gurupawar**
## Checklist

- [ x ] I understand that if I don't put a description or check all of these points, the pull request will not even be looked at
- [ x ] I have read the [contributing guidelines](https://github.com/vivian-dai/Hacktoberfest-2021-Repos/blob/main/CONTRIBUTING.md)
- [ x ] If changes are requested, I understand my pull request will not be merged until all changes are made
- [ x ] My branch is up to date with `main`
- [ x ] I am not just tossing in random files or completely irrelevant things
- [ x ] I will not add a comment, create an issue, or anything similar requesting for this pull request to be reviewed

### CODE REVIEW

**Review by vivian-dai — CHANGES_REQUESTED** [review]
Could you also add the "Leetcode Solutions" category to the table of contents? Thanks.

**Comment by gurupawar** [comment]
Sure

**Comment by gurupawar** [comment]
updated

**Comment by vivian-dai** [comment]
image
check your formatting

**Review by vivian-dai — APPROVED** [review]
LGTM!

**Pull request merged**
