### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BTANISHA11**
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/vivian-dai/Hacktoberfest-2021-Repos/blob/main/CONTRIBUTING.md)
- [x] If changes are requested, I understand my pull request will not be merged until all changes are made
- [x] My branch is up to date with `main`
- [x] I am not just tossing in random files or completely irrelevant things
- [x] I will not add a comment, create an issue, or anything similar requesting for this pull request to be reviewed

### CODE REVIEW

**Comment by BTANISHA11** [comment]
Updated readme.md @vivian-dai

**Review by vivian-dai — CHANGES_REQUESTED** [review]
Could you put the description back and put the topics you just added in alphabetical order? Thanks.

**Comment by BTANISHA11** [comment]
Okk I will do

**Comment by BTANISHA11** [comment]
DONE @vivian-dai

**Review by vivian-dai — APPROVED** [review]
LGTM, thanks for contributing!

**Comment by BTANISHA11** [comment]
Pls add hactoberfest label to it @vivian-dai

**Pull request merged**
