### PR TITLE
Feat(add TTM projects in Web Dev)

### PR DESCRIPTION
**Pull request by Kigamekun**
## Checklist

- [ X] I have read the [contributing guidelines](https://github.com/vivian-dai/Hacktoberfest-2021-Repos/blob/main/CONTRIBUTING.md)
- [X ] If changes are requested, I understand my pull request will not be merged until all changes are made
- [ X] My branch is up to date with `main`
- [ X] I am not just tossing in random files or completely irrelevant things
- [ X] I will not add a comment, create an issue, or anything similar requesting for this pull request to be reviewed

### CODE REVIEW

**Comment by Kigamekun** [comment]
Please add label hacktoberfest and accept  this pull request thank you :)

**Review by vivian-dai — COMMENTED** [review]
Your repository does not have a "hacktoberfest" label. I'll accept your PR after you do that

**Comment by Kigamekun** [comment]
but I can't add a label, more precisely don't know how

**Comment by vivian-dai** [comment]
image
This is how your repository looks like right now. Notice how other repositories have a hacktoberfest label, eg.
image
If you click the settings option
image
you should be able to add "hacktoberfest" as a topic

**Comment by Kigamekun** [comment]
is that so? take a look back at my repo thanks :)

**Comment by vivian-dai** [comment]
Still no "hacktoberfest" topic :(

**Comment by Kigamekun** [comment]
whattt ??

<a href="https://ibb.co/bLrJP08">Screenshot-from-2022-10-01-20-25-32</a>

like this ?

**Comment by vivian-dai** [comment]
Put the "hacktoberfest" topic on your [TTM](https://github.com/Kigamekun/TTM) repo

**Comment by Kigamekun** [comment]
ouhhh okay, looks again

**Review by vivian-dai — APPROVED** [review]
Wonderful! LGTM, happy hacking!

**Pull request merged**
